// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'This E-Commerce app is designed for Android only. '
        'Web platform is not supported.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'This E-Commerce app is designed for Android only. '
          'iOS platform is not supported.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'This E-Commerce app is designed for Android only. '
          'macOS platform is not supported.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'This E-Commerce app is designed for Android only. '
          'Windows platform is not supported.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'This E-Commerce app is designed for Android only. '
          'Linux platform is not supported.',
        );
      default:
        throw UnsupportedError(
          'This E-Commerce app is designed for Android only. '
          'This platform is not supported.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-web-api-key',
    appId: '1:236498123851:web:your-web-app-id',
    messagingSenderId: '236498123851',
    projectId: 'ecom-f2856',
    authDomain: 'ecom-f2856.firebaseapp.com',
    storageBucket: 'ecom-f2856.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkv922Ktn6UgmYGHt9ix9vw_0U2Wq4jo4',
    appId: '1:236498123851:android:d7f5bf9be8ff25f99ce1ce',
    messagingSenderId: '236498123851',
    projectId: 'ecom-f2856',
    storageBucket: 'ecom-f2856.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: '1:236498123851:ios:your-ios-app-id',
    messagingSenderId: '236498123851',
    projectId: 'ecom-f2856',
    storageBucket: 'ecom-f2856.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: '1:236498123851:ios:your-macos-app-id',
    messagingSenderId: '236498123851',
    projectId: 'ecom-f2856',
    storageBucket: 'ecom-f2856.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
